name: findge
description: FinEdge Africa — éducation financière mobile (Flutter).
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  go_router: ^16.2.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/animations/
  # Police Matt (Fontfabric) — déposer Regular/Medium/Bold/Black ici :
  # fonts:
  #   - family: Matt
  #     fonts:
  #       - asset: assets/fonts/Matt-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Matt-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Matt-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Matt-Black.ttf
  #         weight: 900
